spring:
  config:
    import: optional:secret/application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/auth/signup
      method: POST
    - path-pattern: /api/auth/login
      method: POST
    - path-pattern: /api/auth/login/*
      method: POST
    - path-pattern: /api/auth/reissue
      method: POST
    - path-pattern: /api/auth/verify
      method: POST
    - path-pattern: /api/auth/oauth2/callback/**
      method: GET
    - path-pattern: /api/email/**
      method: POST
    - path-pattern: /swagger-ui.html
      method: GET
    - path-pattern: /swagger-ui/index.html
      method: GET
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs
      method: GET
    - path-pattern: /v3/api-docs/swagger-config
      method: GET
    - path-pattern: /actuator/**
      method: GET
    - path-pattern: /**
      method: OPTIONS

exclude-blacklist-path-patterns:
  paths:
    - path-pattern: /api/auth/signup
      method: POST
    - path-pattern: /api/auth/login
      method: POST
    - path-pattern: /api/auth/login/*
      method: POST
    - path-pattern: /api/auth/reissue
      method: POST
    - path-pattern: /api/auth/verify
      method: POST
    - path-pattern: /api/auth/oauth2/callback/**
      method: GET
    - path-pattern: /api/email/**
      method: POST
    - path-pattern: /swagger-ui.html
      method: GET
    - path-pattern: /swagger-ui/index.html
      method: GET
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs
      method: GET
    - path-pattern: /v3/api-docs/swagger-config
      method: GET
    - path-pattern: /actuator/**
      method: GET
    - path-pattern: /**
      method: OPTIONS

cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,Accept"
  max-age: 3600

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    groups-order: DESC # path, query, body, response 순서대로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method # delete - get - patch - post - put 순으로 정렬
    enabled: true
  paths-to-match:
    - /api/**

# OAuth2 Provider endpoints (public, non-secret)
auth:
  oauth2:
    providers:
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
        scope: "openid,profile,email"
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        scope: "name,email,profile_image"
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        scope: "profile_nickname,profile_image,account_email"