# Auth 서비스 ArgoCD Application
# 이 파일은 인프라 레포에서 관리될 예정
# 참고용으로만 남겨둠

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youthfi-auth-service
  namespace: argocd
  labels:
    app: youthfi-auth-service
    component: auth
spec:
  project: default
  source:
    repoURL: https://github.com/KE-WhyNot/BE-auth-service
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
